[project]
name = "purchasing-anomaly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv",
    "ipykernel",
    "pandas",
    "snowflake",
    "snowflake-ml-python",
    "pip<25.0",
]
